# Generated by Django 5.0.4 on 2024-04-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="hospitaladmin",
            name="user",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="HospitalAdmin",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
