# Generated by Django 5.0.4 on 2024-04-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_doctor_biography_doctor_date_of_birth_doctor_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="Name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
